runtime: python27
api_version: 1
threadsafe: true

env_variables:
  CLOUD_SQL_CONNECTION_NAME: itesm-exchange:us-central1:backend
  DB_USER: kaleb
  DB_PASS: kaleb
  DB_NAME: itesm_exchange

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /bootstrap-4.2.1-dist
  static_dir: bootstrap-4.2.1-dist

- url: /
  static_files: views/login.html
  upload: viws/login.html

- url: /(.*)
  static_files: views/\1
  upload: views/(.*)